Revert "update (#25)"
This reverts commit 3c2fe39a27c52a2922b9745857bdf6dcee4450a9.

| mipsel-oe-linux-g++  -mel -mabi=32 -mhard-float -march=mips32 --sysroot=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../git     -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/git=/usr/src/debug/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0  -fdebug-prefix-map=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/git=/usr/src/debug/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0  -fmacro-prefix-map=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/build=/usr/src/debug/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0  -fdebug-prefix-map=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/build=/usr/src/debug/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0  -fdebug-prefix-map=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/recipe-sysroot=  -fmacro-prefix-map=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/recipe-sysroot=  -fdebug-prefix-map=/home/oe1/atv72mipsel/build-enviroment/builds/openatv/release/ultramini/tmp/work/ultramini-oe-linux/satipclient/1.0+gitAUTOINC+3c2fe39a27-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -c -o vtuner.o ../git/vtuner.cpp
| ../git/manager.cpp: In member function 'int sessionManager::satipStart()':
| ../git/manager.cpp:59:43: error: no matching function for call to 'sessionManager::satipSessionCreate(const char*, int&)'
|    59 |                         satipSessionCreate(it->second.m_ipaddr.c_str(), it->second.m_fe_type);
|       |                         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In file included from ../git/manager.cpp:23:
| ../git/manager.h:39:13: note: candidate: 'int sessionManager::satipSessionCreate(const char*, int, const char*, vtunerOpt*)'
|    39 |         int satipSessionCreate(const char* ipaddr, int fe_type, const char *port, vtunerOpt* settings);
|       |             ^~~~~~~~~~~~~~~~~~
| ../git/manager.h:39:13: note:   candidate expects 4 arguments, 2 provided
| make[1]: *** [Makefile:438: manager.o] Error 1